### ISSUE TITLE
Make delete buttons functional.

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/todo_app#1]
Make the delete button next to every list item functional such that on pressing it, the list item gets deleted..

**Comment by Sakshi2002-Sinha** [comment]
hello, Can you please assign me this issue?

**Comment by AashishKatila** [comment]
Hello @tarushi0503 I am a newbie here but would like to fix the above issue so could you assign it to me.

**Comment by yash2107** [comment]
I want to solve this issue.
Thanks.

**Comment by tarushi0503** [comment]
I have assigned the issue to all of you. @yash2107 @AashishKatila @Sakshi2002-Sinha . All the best.
