### ISSUE TITLE
Improve UI of the delete buttons

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/todo_app#2]
Improve UI of the delete buttons next to every list item.

**Comment by Anant2961** [comment]
Can you please assign me this project

**Comment by tanyaa-arora** [comment]
Hi @tarushi0503 I'd like to work on the issue. Kindly assign it to me

**Comment by sonal3yadav** [comment]
I would like to work on this issue please assign this issue to me

**Comment by tarushi0503** [comment]
Assigned. @sonal3yadav @tanyaa-arora @Anant2961

**Comment by Code-Techy** [comment]
## Hello **@tarushi0503** 
 **As a beginner to open source, I would like to contribute to your repository,
I have experience with the Flutter Framework and would appreciate if you could assign this issue to me.**

**Comment by yash2107** [comment]
I want to solve this issue.
