### ISSUE TITLE
Make '+' button functional

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/todo_app#3]
Add functionality to '+' button such that whatever is typed in the text box is added to the to-do list on clicking '+'

**Comment by Gowrishankar04** [comment]
Hi @tarushi0503 ,

Can you please assign this to me?

Thanks

**Comment by PrajwalGKale** [comment]
## Greetings, **`@tarushi0503`**
> **I was looking for a repository to contribute to open source and found this one.**
    **Can you assign this to me? I'm familiar with the Flutter framework . I'd love to do it.**

-*Regards, thanks.* 😄

**Comment by yash2107** [comment]
I want to work on this issue. 
Thanks.

**Comment by tarushi0503** [comment]
I have assigned the issue to all three of you @yash2107 @PrajwalGKale @Gowrishankar04 . All the best.
