### ISSUE TITLE
Remove all the warnings

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/todo_app#4]
Remove warnings to make code problem-free and for its easy code readability.

**Comment by PrajwalGKale** [comment]
## Greetings, **`@tarushi0503`**
> **I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Flutter framework* . I'd love to do it.**

-*Regards, thanks.* 😄

**Comment by tarushi0503** [comment]
I have assigned you the issue. @PrajwalGKale All the best.

**Comment by sonal3yadav** [comment]
I would like to work on this issue please assign this issue to me

**Comment by tarushi0503** [comment]
Assigned. @sonal3yadav

**Comment by PrajwalGKale** [comment]
## Hello , **`@tarushi0503`** 
> **The issue was assigned to me, and I made all the requested changes.
    But I am not able to push the changes into the master branch.**
**Issue : "remote: Permission to tarushi0503/todo_app.git denied to PrajwalGKale."**
_I hope you will help me out_

**Comment by yash2107** [comment]
I am solving this issue.
