### ISSUE TITLE
+ button adds empty tile.

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/todo_app#7]
Change functionality of + button such that when the text box beside it has some text only then new new tile is added not when it is empty.

**Comment by PrajwalGKale** [comment]
## Greetings , **`@tarushi0503  `** 
> **Can you assign this to me? I'm familiar with the *Flutter Framework* . and I would love to do it.**

_-Regards, thanks._ 👾

**Comment by tarushi0503** [comment]
Assigned @PrajwalGKale .
